from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class AIVerdict(BaseModel):
    """Structured phishing verdict generated by Claude AI."""

    verdict: Literal["phishing", "suspicious", "legitimate", "unknown"]
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence 0.0–1.0")
    executive_summary: str = Field(..., description="1–2 sentence plain-language summary for SOC analysts")
    key_indicators: list[str] = Field(
        default_factory=list,
        description="Specific evidence items that drove the verdict",
    )
    recommended_action: str = Field(
        ...,
        description="Concrete next step (e.g. 'Block domain at perimeter firewall')",
    )
    model: str = Field(..., description="AI model ID that produced this verdict")
    cached: bool = Field(default=False, description="Reserved for future response caching")
